/** Throwaway visual experiment. Same scene/collision, four representations; no world API writes. */
import * as pc from 'playcanvas';
import type {CollisionBox, Vec3} from '../../../../packages/protocol/src/index.ts';
import {boundary,chunkBoxes,placements,route,start,step,overlaps} from './spatial.ts';
import {acceptComposition,approachRoute,express,freshWorld,gesture,inReach,nextPlacements,observeCrossing,restoreWorld,scratchKey,thresholdBoxes,type PrototypeWorld} from './threshold-state.ts';
import {buildSolidGlyph,classifyStressFace} from './treatments.ts';
import {buildThresholdView} from './threshold-view.ts';

type SceneData={sources:unknown;transform:{scale:number;position:Vec3};mesh:{positions:number[];normals:number[];indices:number[]};boxes:CollisionBox[];glyphs:Vec3[];metrics:Record<string,number>;bounds:{min:Vec3;max:Vec3};caveats:string[]};
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const canvas=el<HTMLCanvasElement>('inspection-canvas');
const app=new pc.Application(canvas,{graphicsDeviceOptions:{antialias:false,alpha:false,powerPreference:'high-performance'}});
app.graphicsDevice.maxPixelRatio=Math.min(devicePixelRatio,1.5);app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);app.setCanvasResolution(pc.RESOLUTION_AUTO);
const camera=new pc.Entity('observer');camera.addComponent('camera',{fov:65,nearClip:.07,farClip:70,clearColor:new pc.Color(.055,.085,.11)});app.root.addChild(camera);
app.scene.ambientLight=new pc.Color(.35,.4,.42);
const sun=new pc.Entity('sun');sun.addComponent('light',{type:'directional',color:new pc.Color(.95,.82,.62),intensity:1.4});sun.setEulerAngles(45,30,0);app.root.addChild(sun);
let solidTreatment:ReturnType<typeof buildSolidGlyph>,nextTreatment:ReturnType<typeof buildSolidGlyph>,facetedMesh:pc.Mesh;let cleanColors:number[]=[],faultColors:number[]=[];let stress=new URLSearchParams(location.search).get('stress')==='1';
const roots: Record<string,pc.Entity>={};for(const key of ['faceted','glyph','splats','collider']){roots[key]=new pc.Entity(key);app.root.addChild(roots[key]);}
let data:SceneData,boxes:CollisionBox[]=[],position:Vec3=[...start],yaw=0,pitch=5,ready=false,inspection=false,showCollider=false;
let activeRoute=route;
let intentionMode=new URLSearchParams(location.search).get('experiment')==='intention',world:PrototypeWorld=restoreWorld(sessionStorage.getItem(scratchKey)),thought=0,thoughtKind='',forming=0;
let auto=0,tourIndex=-1,tourDistance=0,collisions=0,travel=0,variant='hybrid',last=0,frameTimes:number[]=[],loadMs=0;
document.querySelectorAll<HTMLButtonElement>('footer button').forEach(b=>b.disabled=true);el<HTMLSelectElement>('variant').disabled=true;
const keys=new Set<string>();let drag=false;let previousX=0,previousY=0;
function material(color:number[],lit=true){const m=new pc.StandardMaterial();m.diffuse=new pc.Color(...color);m.useLighting=lit;m.emissive=lit?new pc.Color(0,0,0):new pc.Color(...color);m.metalness=0;m.gloss=0;m.update();return m;}
function boxEntity(b:CollisionBox,parent:pc.Entity,m:pc.Material){const e=new pc.Entity();e.addComponent('render',{type:'box',material:m});e.setPosition(...b.min.map((n,i)=>(n+b.max[i])/2) as Vec3);e.setLocalScale(...b.min.map((n,i)=>b.max[i]-n) as Vec3);parent.addChild(e);return e;}
const scaffold=material([.12,.20,.22]);const scaffoldWalls=boundary.map(b=>boxEntity(b,app.root,scaffold));
const thresholdView=buildThresholdView(app);thresholdView.root.enabled=false;
const nextRoot=new pc.Entity('next generated forms');app.root.addChild(nextRoot);nextRoot.enabled=false;
// Authored floor markings expose stable depth and route continuity across all treatments.
const lines=material([.28,.36,.34],false);for(let x=-8;x<=8;x+=2)boxEntity({min:[x-.012,.001,-10.8],max:[x+.012,.007,8.8]},app.root,lines);for(let z=-10;z<=8;z+=2)boxEntity({min:[-8.8,.001,z-.012],max:[8.8,.007,z+.012]},app.root,lines);
function makeMesh(positions:number[],indices:number[],normals?:number[],uvs?:number[],colors?:number[]){const mesh=new pc.Mesh(app.graphicsDevice);mesh.setPositions(positions);mesh.setIndices(indices);if(normals)mesh.setNormals(normals);if(uvs)mesh.setUvs(0,uvs);if(colors)mesh.setColors(colors);mesh.update(pc.PRIMITIVE_TRIANGLES);return mesh;}
function addMesh(mesh:pc.Mesh,mat:pc.Material,parent:pc.Entity,p:Vec3,scaled=false){const e=new pc.Entity();e.addComponent('render',{meshInstances:[new pc.MeshInstance(mesh,mat)]});e.setPosition(...p);if(scaled){e.setLocalScale(data.transform.scale,data.transform.scale,data.transform.scale);e.translate(...data.transform.position);}parent.addChild(e);return e;}
function buildFaceted(){const {positions:v,indices:f}=data.mesh;const p:number[]=[],n:number[]=[],c:number[]=[],idx:number[]=[];const palette=[[.16,.34,.37],[.48,.65,.57],[.85,.68,.40],[.23,.27,.36]];
 for(let i=0;i<f.length;i+=3){const a=f[i]*3,b=f[i+1]*3,d=f[i+2]*3;const ab=[v[b]-v[a],v[b+1]-v[a+1],v[b+2]-v[a+2]],ac=[v[d]-v[a],v[d+1]-v[a+1],v[d+2]-v[a+2]];const normal=[ab[1]*ac[2]-ab[2]*ac[1],ab[2]*ac[0]-ab[0]*ac[2],ab[0]*ac[1]-ab[1]*ac[0]];const len=Math.hypot(...normal)||1;const color=palette[Math.abs(Math.floor((v[a+1]+.5)*8)+Math.floor(normal[1]/len*2))%palette.length];for(const k of [a,b,d]){idx.push(idx.length);p.push(v[k],v[k+1],v[k+2]);n.push(...normal.map(x=>x/len));c.push(...color,1);}}
 cleanColors=c;faultColors=[...c];for(let i=0;i<f.length;i+=3){const kind=classifyStressFace(data,i/3);if(kind){const fault=kind==='corrupt'?(i%2?[1,.015,.68]:[.08,1,.06]):[.7,.7,.7];for(let j=0;j<3;j++)faultColors.splice((i+j)*4,4,...fault,1);}}
 const mesh=makeMesh(p,idx,n,undefined,c);facetedMesh=mesh;const m=material([1,1,1]);m.diffuseVertexColor=true;m.update();for(const pos of placements)addMesh(mesh,m,roots.faceted,pos,true);
}
function buildGlyphs(){const atlas=document.createElement('canvas');atlas.width=256;atlas.height=32;const ctx=atlas.getContext('2d')!;ctx.font='bold 28px monospace';ctx.fillStyle='white';ctx.textAlign='center';const chars=['+','#',':','/','|','×','•','◇'];chars.forEach((ch,i)=>ctx.fillText(ch,i*32+16,25));const texture=new pc.Texture(app.graphicsDevice,{mipmaps:false});texture.setSource(atlas);
 const m=material([0,0,0],false);m.emissive=new pc.Color(.61,.85,.63);m.emissiveMap=texture;m.opacityMap=texture;m.opacityMapChannel='a';m.alphaTest=.2;m.cull=pc.CULLFACE_NONE;m.update();const p:number[]=[],uv:number[]=[],idx:number[]=[];
 data.glyphs.forEach((q,i)=>{const size=.11;const glyph=i%8;for(const axis of [0,2]){const base=p.length/3;for(const [u,v] of [[0,0],[1,0],[1,1],[0,1]]){const pt=[...q];pt[axis]+=(u-.5)*size;pt[1]+=(v-.5)*size;p.push(...pt);uv.push((glyph+u)/8,v);}idx.push(base,base+1,base+2,base,base+2,base+3);}});
 const mesh=makeMesh(p,idx,undefined,uv);for(const pos of placements)addMesh(mesh,m,roots.glyph,pos);
}
function apply(){if(intentionMode){inspection=false;showCollider=false;}el<HTMLButtonElement>('mode').disabled=intentionMode;el<HTMLButtonElement>('collider').disabled=intentionMode;solidTreatment.root.enabled=variant==='solid'||variant==='hybrid';solidTreatment.setMode(variant==='hybrid'?'hybrid':'solid');solidTreatment.setStress(stress);solidTreatment.root.children.forEach((e,i)=>e.enabled=!inspection||i===0);nextTreatment.setMode('hybrid');nextTreatment.setStress(stress);facetedMesh.setColors(stress?faultColors:cleanColors);facetedMesh.update(pc.PRIMITIVE_TRIANGLES);el('stress').textContent=stress?'Stress ON · material faults':'Stress OFF';roots.faceted.enabled=variant==='faceted';roots.glyph.enabled=variant==='glyph';roots.splats.enabled=variant==='original'||variant==='graphic';roots.collider.enabled=showCollider;canvas.classList.toggle('graphic',variant==='graphic');for(const name of ['faceted','glyph','splats'])roots[name].children.forEach((e,i)=>e.enabled=!inspection||i===0);roots.collider.children.forEach((e,i)=>e.enabled=i===0||!inspection||i===1);boxes=intentionMode?thresholdBoxes(data.boxes,world):chunkBoxes(data.boxes,inspection);scaffoldWalls[3].enabled=!intentionMode;thresholdView.root.enabled=intentionMode;nextRoot.enabled=intentionMode&&!!world.threshold.composition;el('intention-cue').hidden=!intentionMode;el<HTMLDetailsElement>('lab-controls').open=!intentionMode;el('scene-kind').textContent=intentionMode?'Real TRELLIS forms × 6 · Controlled composition · Scratch world only':'Real TRELLIS forms × 3 · Fixed geometry / collision · No M0 saves';el('threshold-mode').textContent=intentionMode?'Visual comparison':'Intention threshold';frameTimes=[];el('status').textContent=`${inspection?'ONE ASSET':'DISPOSABLE CHUNK'} · ${variant} · ${(data.bounds.max[1]-data.bounds.min[1]).toFixed(2)} m tall · ${boxes.length} collision boxes`;}
function reset(){auto=0;tourIndex=-1;thought=0;position=[...start];yaw=0;pitch=5;keys.clear();}
function stop(){auto=0;tourIndex=-1;thought=0;keys.clear();drag=false;}
function changeVariant(){variant=el<HTMLSelectElement>('variant').value;const url=new URL(location.href);url.searchParams.set('variant',variant);history.replaceState(null,'',url);apply();}
el('stress').onclick=()=>{stress=!stress;const url=new URL(location.href);url.searchParams.set('stress',stress?'1':'0');history.replaceState(null,'',url);apply();};
el('variant').addEventListener('change',changeVariant);el('reset').onclick=reset;
el('side').onclick=()=>{reset();position=[6.8,1.65,0];yaw=90;pitch=8;};el('back').onclick=()=>{reset();position=[0,1.65,-3];yaw=180;pitch=8;};
el('mode').onclick=()=>{inspection=!inspection;el('mode').textContent=inspection?'Explore chunk':'Inspect one asset';reset();apply();};
el('collider').onclick=()=>{showCollider=!showCollider;el('collider').textContent=showCollider?'Hide collider':'Show collider';apply();};
el('forward').onclick=()=>{auto=1;tourIndex=-1;};el('stop').onclick=stop;
el('tour').onclick=()=>{reset();activeRoute=route;tourIndex=0;tourDistance=0;el('check-result').textContent='Walking circuit through the live collision system…';};
el('enter').onclick=()=>{canvas.focus();try{void canvas.requestPointerLock()?.catch(()=>{});}catch{}};
function saveWorld(){sessionStorage.setItem(scratchKey,JSON.stringify(world));el('world-record').textContent=JSON.stringify(world,null,2);el('world-record').dataset.state=JSON.stringify(world);}
function updateWorld(){saveWorld();thresholdView.compose(world);apply();}
el('threshold-mode').onclick=()=>{intentionMode=!intentionMode;inspection=false;reset();const url=new URL(location.href);if(intentionMode)url.searchParams.set('experiment','intention');else url.searchParams.delete('experiment');history.replaceState(null,'',url);apply();};
el('approach').onclick=()=>{if(!intentionMode){intentionMode=true;apply();}reset();activeRoute=approachRoute;tourIndex=0;tourDistance=0;};
el('return-seam').onclick=()=>{if(!intentionMode||position[2]>-11)return;auto=0;activeRoute=[[0,1.65,-12],[0,1.65,-9]];tourIndex=0;tourDistance=0;};
el('upward').onclick=()=>{stop();pitch=35;yaw=0;};el('ahead').onclick=()=>{stop();pitch=0;yaw=0;};
el('fresh-world').onclick=()=>{world=freshWorld();forming=0;reset();updateWorld();};
canvas.addEventListener('pointerdown',e=>{drag=true;previousX=e.clientX;previousY=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.focus();});canvas.addEventListener('pointerup',()=>drag=false);
document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){yaw-=e.movementX*.12;pitch-=e.movementY*.12;}else if(drag){yaw-=(e.clientX-previousX)*.12;pitch-=(e.clientY-previousY)*.12;previousX=e.clientX;previousY=e.clientY;}pitch=Math.max(-80,Math.min(80,pitch));});
document.addEventListener('keydown',e=>{if(e.code==='Escape'){stop();document.exitPointerLock();}if(e.code==='KeyE'&&!e.repeat&&intentionMode&&inReach(position)&&world.threshold.phase==='unshaped'){thought=thought?0:.001;thoughtKind=gesture(pitch);e.preventDefault();}if(e.target instanceof HTMLSelectElement)return;if(['KeyW','KeyA','KeyS','KeyD','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code)){keys.add(e.code);auto=0;tourIndex=-1;e.preventDefault();}});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
function checks(){const checks:Record<string,unknown>={};let p:Vec3=[...start];for(let i=0;i<500;i++)p=step(p,0,-.05,boxes);checks.generatedObstacleStops=p[2]>-1&&p[2]<3;checks.obstacleStop=p;let q:Vec3=[7,1.65,7];for(let i=0;i<500;i++)q=step(q,.05,0,boxes);checks.boundaryStops=Math.abs(q[0]-8.5)<.02;checks.boundaryStop=q;let r:Vec3=[...start],distance=0;let completed=true;for(const target of route){for(let i=0;i<1000;i++){const dx=target[0]-r[0],dz=target[2]-r[2],len=Math.hypot(dx,dz);if(len<.035)break;const next=step(r,dx/len*Math.min(.04,len),dz/len*Math.min(.04,len),boxes);distance+=Math.hypot(next[0]-r[0],next[2]-r[2]);if(overlaps(next,boxes)||Math.hypot(next[0]-r[0],next[2]-r[2])<.00001){completed=false;break;}r=next;}if(!completed)break;}checks.circuitReturns=completed&&Math.hypot(r[0]-start[0],r[2]-start[2])<.04;checks.circuitDistance=distance;checks.end=r;checks.pass=checks.generatedObstacleStops&&checks.boundaryStops&&checks.circuitReturns;el('check-result').textContent=JSON.stringify(checks,null,2);el('check-result').dataset.result=JSON.stringify(checks);}
el('check').onclick=checks;
app.on('update',(elapsed:number)=>{if(!ready)return;const dt=Math.min(elapsed,.05);frameTimes.push(elapsed*1000);if(frameTimes.length>600)frameTimes.shift();let dx=0,dz=0;
 if(tourIndex>=0){const target=activeRoute[tourIndex],vx=target[0]-position[0],vz=target[2]-position[2],dist=Math.hypot(vx,vz);if(dist<.09){tourIndex++;if(tourIndex===activeRoute.length){tourIndex=-1;el('check-result').textContent=`Live route complete · ${tourDistance.toFixed(2)} m`;}}else{dx=vx/dist*dt*2.5;dz=vz/dist*dt*2.5;yaw=Math.atan2(-vx,-vz)*180/Math.PI;pitch=2;}}
 else{yaw+=((keys.has('ArrowLeft')?1:0)-(keys.has('ArrowRight')?1:0))*dt*70;pitch+=((keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0))*dt*50;const forward=auto+(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),right=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),len=Math.hypot(forward,right)||1,r=yaw*Math.PI/180;dx=(-Math.sin(r)*forward+Math.cos(r)*right)/len*dt*2.5;dz=(-Math.cos(r)*forward-Math.sin(r)*right)/len*dt*2.5;}
 const next=step(position,dx,dz,boxes),moved=Math.hypot(next[0]-position[0],next[2]-position[2]);if(Math.hypot(dx,dz)-moved>.001)collisions++;travel+=moved;if(tourIndex>=0)tourDistance+=moved;const previous=position;position=next;if(intentionMode){const observed=observeCrossing(world,previous,position);if(observed!==world){world=observed;saveWorld();}}camera.setPosition(...position);camera.setEulerAngles(pitch,yaw,0);
 solidTreatment.update(position);nextTreatment.update(position);
 if(intentionMode){
 if(thought){if(!inReach(position)||gesture(pitch)!==thoughtKind)thought=0;else{thought+=dt;if(thought>=1.1){world=express(world,gesture(pitch),position);thought=0;forming=0;updateWorld();}}}
 if(world.threshold.phase==='forming'){forming+=dt/1.8;if(forming>=1){world=acceptComposition(world);updateWorld();}}
 thresholdView.update(world,forming,position);
 const phase=world.threshold.phase;el('intention-cue').textContent=phase==='unshaped'?(inReach(position)?(thought?`Holding ${thoughtKind} · ${Math.round(thought/1.1*100)}%`:'Look up: Ascend · Look into the opening: Seek · E to hold the thought'):'An unformed threshold waits beyond the forms.') : phase==='forming'?`The space answers ${world.threshold.intention}…`:phase==='ready'?`${world.threshold.intention==='ascend'?'The space opens upward.':'Traces gather toward something hidden.'} Cross when ready.`:'This place remembers your intention. You can return.';
 }
 if(performance.now()-last>250){last=performance.now();const sorted=[...frameTimes].sort((a,b)=>a-b);const state={variant,stress,glyphsVisible:solidTreatment.stats.visibleGlyphs,nextGlyphsVisible:nextTreatment.stats.visibleGlyphs,inspection,intentionMode,worldPhase:world.threshold.phase,intention:world.threshold.intention,thought:+thought.toFixed(2),pitch:+pitch.toFixed(1),position:position.map(n=>+n.toFixed(3)),yaw:+yaw.toFixed(1),travelMetres:+travel.toFixed(2),collisionFrames:collisions,overlaps:overlaps(position,boxes),frameMedianMs:+(sorted[Math.floor(sorted.length*.5)]||0).toFixed(2),frameP95Ms:+(sorted[Math.floor(sorted.length*.95)]||0).toFixed(2),samples:sorted.length,loadMs:+loadMs.toFixed(1),tourIndex};el('telemetry').textContent=`Position ${state.position.join(' / ')} · ${state.frameMedianMs} ms/frame · collisions ${collisions} · ${travel.toFixed(1)} m walked`;el('telemetry').dataset.state=JSON.stringify(state);}
});
async function boot(){const t=performance.now();const response=await fetch('/m1-prototype/scene.json');if(!response.ok)throw new Error('Run npm run m1 to prepare the verified benchmark artifacts');data=await response.json();buildFaceted();buildGlyphs();
 solidTreatment=buildSolidGlyph(app,data,placements);app.root.addChild(solidTreatment.root);nextTreatment=buildSolidGlyph(app,data,nextPlacements);nextRoot.addChild(nextTreatment.root);thresholdView.compose(world);saveWorld();const colliderMaterial=material([.96,.31,.14],false);colliderMaterial.opacity=.25;colliderMaterial.blendType=pc.BLEND_NORMAL;colliderMaterial.depthWrite=false;colliderMaterial.update();const support=new pc.Entity('support');roots.collider.addChild(support);for(const b of boundary)boxEntity(b,support,colliderMaterial);for(const pos of placements){const group=new pc.Entity('derived solid');roots.collider.addChild(group);group.setPosition(...pos);for(const b of data.boxes)boxEntity(b,group,colliderMaterial);}
 const asset=new pc.Asset('verified-trellis','gsplat',{url:'/m1-prototype/scene.ply'});app.assets.add(asset);await new Promise<void>((resolve,reject)=>{asset.once('load',resolve);asset.once('error',reject);app.assets.load(asset);});
 for(const pos of placements){const e=new pc.Entity('trellis-generated');e.addComponent('gsplat',{asset});e.setLocalScale(data.transform.scale,data.transform.scale,data.transform.scale);e.setPosition(...pos.map((x,i)=>x+data.transform.position[i]) as Vec3);roots.splats.addChild(e);}
 const requested=new URLSearchParams(location.search).get('variant');if(requested&&['faceted','graphic','glyph','original','solid','hybrid'].includes(requested))variant=requested;el<HTMLSelectElement>('variant').value=variant;apply();el('evidence').textContent=JSON.stringify({sources:data.sources,treatment:solidTreatment.stats,stressFixture:'2328 exact original faces; corrupted/unfinished material only, no geometry or collision edits',transform:data.transform,metrics:data.metrics,authored:'Flat support floor, perimeter, and three instance translations',persistence:'Pose in memory; intention scratch world in prototype-only sessionStorage; no world/player API requests'},null,2);loadMs=performance.now()-t;ready=true;document.querySelectorAll<HTMLButtonElement>('footer button').forEach(b=>b.disabled=false);el<HTMLSelectElement>('variant').disabled=false;apply();}
app.start();window.addEventListener('resize',()=>app.resizeCanvas());void boot().catch(e=>{el('error').textContent=String(e);el('status').textContent='Prototype unavailable';});
