"""Copy study evidence (not source meshes) and bind every retained file by SHA256."""
import hashlib,json,shutil
from pathlib import Path
root=Path(__file__).resolve().parents[2]
src=root/'.runtime/interpretation-study'
dst=root/'docs/research/evidence/generated-space-interpretation-20260916'
dst.mkdir(parents=True,exist_ok=True)
files=[]
for name in ['selections.json','selections.sha256','summary.json','original-integrity.json','final-integrity.json','restart-verification.json','method-freeze.json','source-statistics.json']:
 if (src/name).exists():files.append(src/name)
files.extend(p for p in (src/'candidates').rglob('*') if p.is_file() and p.suffix in ['.json','.png'])
files.extend(p for p in (src/'inspection').glob('*.json') if p.name!='index.json')
records=[]
for p in files:
 rel=p.relative_to(src);out=dst/rel;out.parent.mkdir(parents=True,exist_ok=True)
 if not out.exists() or out.read_bytes()!=p.read_bytes():shutil.copyfile(p,out)
 records.append({'path':str(rel),'bytes':out.stat().st_size,'sha256':hashlib.sha256(out.read_bytes()).hexdigest()})
(dst/'manifest.json').write_text(json.dumps({'schemaVersion':1,'files':sorted(records,key=lambda r:r['path']),'sourceArtifacts':'Original GLB/PLY remain unchanged in .runtime/reliability/candidates. Original hashes in selections.json and original-integrity.json. No GPU jobs or source copies generated by this study.'},indent=2)+'\n')
print(json.dumps({'files':len(records),'bytes':sum(r['bytes'] for r in records),'destination':str(dst)}))
